sudo: required

language: c

services:
  - docker

env:
  - TEST_SUITE=gnat-6.3
  - TEST_SUITE=gnat-community-2018

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - if [ "$TEST_SUITE" = "gnat-6.3" ]; then docker run -v $PWD:/app -w /app debian:stretch /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends gcc gnat gprbuild make && make && make test"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2018" ]; then docker run -v $PWD:/app -w /app reznik/gnat:gpl.2018.slim /bin/sh -c "make && make test"; fi
