name: CI

on: push

jobs:
    gnat_8_3:
        name: gnat-8.3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: GNAT 8.3 on Posix
              run: docker run -v $PWD:/app -w /app componolit/ci:gnat-fsf-8.3 /bin/sh -c "make && make test"
    gnat_11_2:
        name: gnat-11.2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install Alire
              uses: alire-project/setup-alire@v1
            - name: Install FSF GNAT
              run: |
                make install_gnat_11
            - name: GNAT 11.2 on Posix
              run: |
                eval `make printenv_gnat_11`
                make && make test
    gnat_community_2019:
        name: gnat-community-2019
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2019
                target: native
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2019
                target: arm-elf
            - name: GNAT Community 2019
              run: make test && make REPORT=all proof
            - name: GNAT Community 2019 ARM
              run: $PWD/tests/arm.sh
    gnat_community_2020:
        name: gnat-community-2020
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2020
                target: native
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2020
                target: arm-elf
            - name: GNAT Community 2020
              run: make test && make REPORT=all proof
            - name: GNAT Community 2020 ARM
              run: $PWD/tests/arm.sh
    gnat_community_2021:
        name: gnat-community-2021
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2021
                target: native
            - uses: ada-actions/toolchain@ce2021
              with:
                distrib: community
                community_year: 2021
                target: arm-elf
            - name: GNAT Community 2021
              run: make test && make REPORT=all proof
            - name: GNAT Community 2021 ARM
              run: $PWD/tests/arm.sh
    genode:
        name: Genode
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Genode
              run: docker run -v $PWD:/app componolit/ci:genode /bin/sh -c "/app/tests/genode.sh"
    muen:
        name: Muen
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Muen
              run: docker run -v $PWD:/app componolit/ci:muen /bin/sh -c "/app/tests/muen.sh"
    esp8266:
        name: ESP8266
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: ESP8266
              run: docker run -v $PWD:/app componolit/ci:gnat-community-2019 /bin/sh -c "/app/tests/esp8266.sh"

